# This is a basic workflow to help you get started with Actions.
name: addS3BucketAWS
# Controls when the action will run. 
on:
# Triggers the workflow on push or pull request events but only for the main branch
# push:
#  branches: [ main ]
# Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch: {}
  push:
    branches:
      - 'feature/DeploymentTesting'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"

  deploydev:
    runs-on: ubuntu-latest
    environment: development      
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
    steps:
    - uses: actions/checkout@master
    # Output name of bucket from Environment Variable in Github
    - name: Write Bucket Name
      run: echo "${{ vars.UNIQUE_BUCKET_NAME }}"
    # Create S3 Bucket if it does not exist
    - name: Create S3 Bucket
      run: |
        aws s3api get-bucket-location --bucket ${{ vars.UNIQUE_BUCKET_NAME }} || aws s3 mb s3://${{ vars.UNIQUE_BUCKET_NAME }}
    - name: Set Static Hosting
      run: |
        aws s3 website s3://${{ vars.UNIQUE_BUCKET_NAME }} --index-document index.html

# This workflow contains a single job called "build"
  deployprod:
    needs: deploydev
    runs-on: ubuntu-latest
    environment: production
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
    steps:
    - uses: actions/checkout@master
    # Output name of bucket from Environment Variable in Github
    - name: Write Bucket Name
      run: echo "${{ vars.UNIQUE_BUCKET_NAME }}"
    # Create S3 Bucket if it does not exist
    - name: Create S3 Bucket
      run: |
        aws s3api get-bucket-location --bucket ${{ vars.UNIQUE_BUCKET_NAME }} || aws s3 mb s3://${{ vars.UNIQUE_BUCKET_NAME }}
    - name: Set Static Hosting
      run: |
        aws s3 website s3://${{ vars.UNIQUE_BUCKET_NAME }} --index-document index.html