# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development-build
    strategy:
      matrix:
        node-version: [14.x]
    env:
      VUE_APP_APIURL: ${{ secrets.VUE_APP_APIURL }}
      VUE_APP_COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
      VUE_APP_COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}

    steps:
      - name: Write POOL ID
        run: echo "${{ vars.DEV_COGNITO_USER_POOL_ID  }}"
      - name: Step 1 - Checkout main branch fom GitHub
        uses: actions/checkout@v3
      - name: Step 2 - Choose Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Step 3 - Navigate to client directory and run build
        run: |

          cd client
          npm install
          npm run build --if-present
          npm run lint
          cd ../server
          npm install
          cd ..
          npm install
          npm run unitTest
          npm run test
