name: Performance Load Testing

on:
  pull_request:
    branches: ["main"]

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Go to test folder
        run: |
          cd Test-Automation/Test
          dir

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: performance.js